#!/usr/bin/env bash
#===============================================================================
#
#          FILE: java-version
#
#         USAGE: ./java-version
#
#   DESCRIPTION: Print the current java version.
#
#  REQUIREMENTS: java, head, cut
#        AUTHOR: tung beier
#       CREATED: 11 March 2021 10:54 CET
#===============================================================================

set -o errexit  # Exit when a command fails
# Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails

echo $(java -version 2>&1 | awk -F '"' '/version/ {print $2}')

