#!/usr/bin/env bash
#===============================================================================
#
#          FILE: mic
#
#         USAGE: ./mic
#
#   DESCRIPTION: Change the mic input, signal dwmblocks with signal 11
#                and print out the current volume percentage.
#
#       OPTIONS: up - increase input by 10%
#                down - decrease input by 10%
#  REQUIREMENTS: amixer, dwmblocks, grep, awk, uniq, sed
#        AUTHOR: tung beier
#       CREATED: 11 March 2021 20:31 CET
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails

function getInputLevel() {
    local INPUT_LEVEL=$(amixer get $1 | grep % | awk '{print $5}' | uniq | sed 's/[^0-9]//g')
    echo ${INPUT_LEVEL}
}

function changeInputLevel() {
  case $1 in
    up) amixer -q sset Capture 10%+ ;;
    down) amixer -q sset Capture 10%- ;;
  esac

  pkill -RTMIN+11 dwmblocks
}

if [[ "$#" -eq 1 ]]; then
    changeInputLevel $1
fi

echo "$(getInputLevel Capture)%"

