#!/usr/bin/env bash
#===============================================================================
#
#          FILE: test.sh
#
#         USAGE: ./test.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#         NOTES: ---
#        AUTHOR: tung beier
#       CREATED: 26 September 2021 21:42 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails

cpu_temp=$(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)
gpu_temp=$(nvidia-smi -q -d temperature | grep 'GPU Current Temp' | cut -d':' -f2)
ram=$(free -h | awk '(NR==2){ print $3 }')

echo "${ram} - ${cpu_temp} -${gpu_temp}"

