#!/usr/bin/env bash
#===============================================================================
#
#          FILE: system-status
#
#         USAGE: ./system-status
#
#   DESCRIPTION: Print ram, cpu and gpu information.
#
#  REQUIREMENTS: sed, free, awk (optional: nvidia-smi, grep, cut)
#        AUTHOR: tung beier
#       CREATED: 26 September 2021 21:42 CEST
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails

cpu_temp=$(sed 's/000$/°C/' /sys/class/thermal/thermal_zone0/temp)
ram=$(free -h | awk '(NR==2){ print $3 }')

gpu_temp=''
if command -v nvidia-smi 2&> /dev/null; then
    gpu_temp=$(nvidia-smi -q -d temperature | grep 'GPU Current Temp' | cut -d':' -f2)
    echo "${ram} - ${cpu_temp} -${gpu_temp}"
else
    echo "${ram} - ${cpu_temp}"
fi


