#!/usr/bin/env bash
#===============================================================================
#
#          FILE: volume.sh
#
#         USAGE: ./volume.sh
#
#   DESCRIPTION: Change the volume, signal dwmblocks with signal 10
#                and print out the current volume percentage.
#
#       OPTIONS: up - turn volume up by 10%
#                down - turn volume down by 10%
#  REQUIREMENTS: amixer, dwmblocks, grep, awk, uniq, sed
#        AUTHOR: tung beier
#       CREATED: 16 February 2021 20:19 CET
#===============================================================================

set -o errexit  # Exit when a command fails
                # Use || true if a command is allowed to fail
set -o nounset  # Treat unset variables as an error
set -o pipefail # Exit when a command in a pipeline fails

function getVolumeLevel() {
    local VOLUME_LEVEL=$(amixer get $1 | grep % | awk '{print $5}' | uniq | sed 's/[^0-9]//g')
    echo ${VOLUME_LEVEL}
}

function changeVolumeLevel() {
  case $1 in
    up) amixer -q sset Master 10%+ ;;
    down) amixer -q sset Master 10%- ;;
  esac

  pkill -RTMIN+10 dwmblocks
}

if [[ "$#" -eq 1 ]]; then
    changeVolumeLevel $1
fi

echo "Mic $(getVolumeLevel Capture)% | Vol $(getVolumeLevel Master)%"

